### ISSUE TITLE
Advanced tool sanitation Service level table - missing data incorrectly calculated

### ISSUE THREAD

**Issue by nickdickinson** [ircwash/WASHCost-tool#12]
In this example:
http://washcost.herokuapp.com/en/report/5399b843f3357c0146000005

The missing data is incorrectly calculated. Each column in the Excel sheet should add up to 100%. When the population is under represented, then that means some data is missing. In the first column for example (accessibility), it should indicate 15% for "THERE'S NO DATA FOR THIS"

**Comment by mhig** [comment]
Resolved in latest release
