### ISSUE TITLE
ADVANCED: Water & San  - Impact of missing cost values on report page + inconsistent reporting

### ISSUE THREAD

**Issue by peterburr** [ircwash/WASHCost-tool#13]
IF any cost value is missing inputs
THEN all cost summary data, and the graph, does not appear on the report page
AND "There's no data for this" is reported under inputted expenditure and expenditure surplus/shortfall sections 

The seriously impacts the value of a report given even one missing data point.

Please see example report where the OpEx input for one technology has been removed:
http://washcost.herokuapp.com/en/report/5399bce5d286f03a18000001

This is different to the wireframe (links copied below) totals were reported despite some missing data - and "notices" were given alongside these values listing data gaps.

https://drive.google.com/a/ircwash.org/?tab=mo#folders/0B2A2x4S1vMOXekdkNHdveEF0U2M 

1107_WC_Advanced_Output_Water_DY-01-01.png

**Comment by mhig** [comment]
In the case of the graphing tool, all cost information needs to be present for the tool to operate. The application now correctly reports that there is cost data missing, so the user is prompted to return to the site and complete the cost information to get a full report.

**Comment by nickdickinson** [comment]
Many users will not know all expenditure for a service areas. Many NGOs
will not put in indirect and direct support costs for example. In addition,
cost of capital is sometimes not available. Will users be forced to enter 0
values? The know point of adding “Don’t know” was to allow users to skip it.

Is it possible to have the graph with the indirect and direct support
optional considering that these values are not calculated but straight user
inputs? That would make a big difference. Thanks.

Nick

_From:_ mhig [mailto:notifications@github.com]
_Sent:_ 20 June 2014 09:26
_To:_ ircwash/WASHCost-tool
_Subject:_ Re: [WASHCost-tool] ADVANCED: Water & San - Impact of missing
cost values on report page + inconsistent reporting (#13)

In the case of the graphing tool, all cost information needs to be present
for the tool to operate. The application now correctly reports that there
is cost data missing, so the user is prompted to return to the site and
complete the cost information to get a full report.

—
Reply to this email directly or view it on GitHub
https://github.com/ircwash/WASHCost-tool/issues/13#issuecomment-46651715.[image:
Image removed by sender.]

## 

http://www.irc.nl/page/73684

**Comment by mhig** [comment]
I will consult with the team

**Comment by mhig** [comment]
Graphing has been appropriately updated. Issue resolved.
