### ISSUE TITLE
ADVANCED: Water & San - Cost of capital payback period

### ISSUE THREAD

**Issue by peterburr** [ircwash/WASHCost-tool#14]
IF a cost of capital value is given
BUT the payback period is not specified/left blank
THEN the cost of capital per person cost is given as 0.00 on the report page.
See report:
http://washcost.herokuapp.com/en/report/5399c2bad286f03a18000003

This is misleading, when this is the case the cost of capital should be given as: "There's not enough data for this"

**Comment by mhig** [comment]
Resolved in latest release

**Comment by peterburr** [comment]
This issue is still live

**Comment by mhig** [comment]
Which cost of capital figure is this referring to?

**Comment by peterburr** [comment]
On the report page: The cost of capital values under - inputted expenditure, expected expenditure, expenditure shortfall/surplus 

The are reporting 0.00, but without the input: "what is the payback period of the loan" we cannot say it is zero - but "There's not enough data for this"

Let me know if want any further clarifcation

**Comment by mhig** [comment]
Is this for:

INPUTTED EXPENDITURE (PER PERSON PER YEAR) – COST OF CAPTIAL
EXPECTED EXPENDITURE (PER PERSON PER YEAR) - COST OF CAPITAL
EXPENDITURE SURPLUS/SHORTFALL (PER PERSON PER YEAR) - Cost of capital

AND

AFFORDABILITY OF INPUTTED EXPENDITURE FOR ACTUAL USERS - Cost of capital
( and Percentage of household income)
AFFORDABILITY OF INPUTTED EXPENDITURE FOR DESIGNED NUMBER OF USERS - Cost of capital
( and Percentage of household income)
AFFORDABILITY OF EXPECTED EXPENDITURE FOR ACTUAL USERS - Cost of capital
( and Percentage of household income)

?

**Comment by nickdickinson** [comment]
Just to clarify. Here is an example:
http://washcost.herokuapp.com/en/report/53a9c463676012012d000003

In this example. The COC is shown as 0 under inputted, expected and expenditure surplus/shortfall. It should rather report that there is not enough data.

Under affordability it is ok because we are testing for affordability for the first year and we can assume that the payback period is more than a year in most cases...

**Comment by mhig** [comment]
This has been resolved.
