### ISSUE TITLE
OAuth: Cannot use default authorization_code grant method // please check

### ISSUE THREAD

**Issue by nickdickinson** [ircwash/WASHCost-tool#16]
I've tried to use OAuth to access the API but it has been very difficult.

I am able to use the authorization link provided in the control panel and if I change the response_type from "code" to "token" then I can use a temporary two hour token to access the API.

However, the default flow of requesting a code and then a token does not seem to be working. I also could not pass the password and username in the password grant type.

These are  meant to be supported according to the doorkeeper documentation:
https://github.com/doorkeeper-gem/doorkeeper/wiki/API-endpoint-descriptions-and-examples

Can you please check if this is working from another computer and post the series of requests that you used with their parameters? THis is currently missing in the wiki.

The request that is failing with a 401 code is:

POST http://washcost.herokuapp.com/oauth/token
grant_type: authorization_code
client_id: eb164195c8a8c9bef081223df36b5e28b558244118d0ca8ef48e39f58bd33759
client_secret: 8a30c0ad86d5e7d31534f986f840efbbeda7cca7740dceef2b81ce5e964df798
code: b066d93965941a9ed6dfb1a0cd2a799fce8fa539468cefcffd8c2b647e3d3251
redirect_uri: urn:ietf:wg:oauth:2.0:oob
Content-Type: text/xml

 -- response --
401 Unauthorized
Cache-Control:  no-store

Content-Type:  application/json; charset=utf-8

Date:  Fri, 13 Jun 2014 07:42:54 GMT

Pragma:  no-cache

Server:  thin 1.5.0 codename Knife

X-Rack-Cache:  invalidate, pass

X-Request-Id:  3a4280f3-e4cd-4318-ac09-02a94960e661

X-Runtime:  0.005560

X-Ua-Compatible:  IE=Edge,chrome=1

Transfer-Encoding:  chunked

Connection:  keep-alive

{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an unsupported parameter value, or is otherwise malformed."}

**Comment by mhig** [comment]
Doorkeeper docs should not be used for this - that is the underlying library and it has different settings and options depending on what you are trying to achieve.

This is a standard OAuth2 setup.
1. An application is setup on the WASHcost system with a callback url (callback url is an endpoint on the request server)
2. Keys are generated for this application
3. The Application makes a request with these keys and it’s callback url
4. WASHCcost system authorises and posts back to the supplied callback url the necessary access token
5. The Application then has this token which was consumed by it’s URL
6. Using this token and passing it with each request it can then access the various API endpoints

Users requiring access to the API should write standard OAuth2 logic to interface with it.

**Comment by nickdickinson** [comment]
Please document the actual logic supported and modify the authorise link
(callback) that is provided to the application as it is incorrectly
indicating the code method in that case.

The logic that you are using needs to be outlined and documented with the
parameters that are supported by the WASHCost app.

Typically a server will use the code authorisation method and not request a
token directly. Also, doorkeeper application management generates an
authorisation URL like this one for:
http://washcost.herokuapp.com/oauth/authorize?client_id=eb164195c8a8c9bef081223df36b5e28b558244118d0ca8ef48e39f58bd33759&redirect_uri=https%3A%2F%2Fscript.google.com%2Fmacros&response_type=code

On this page:

http://washcost.herokuapp.com/oauth/applications/5396ea2e72b4371bd7000001

That URL is clearly identifying the response_type as code and not as token,
which means the default is to pass a code and then request a token (as
noted in Doorkeeper which you had previously identified as the OAuth
implementation).

If you are using the workflow indicated, then it is the wrong link.

A note on OAuth2. This should have been documented and still needs further
details as the OAuth2 standard has many methods for different types of
devices and applications. It is actually quite complex with many
implementation. Note even large service providers (Twitter, Google, etc.)
use different logic and usually support several methods (as does
doorkeeper):
https://aaronparecki.com/articles/2012/07/29/1/oauth2-simplified

Best,

Nick

_From:_ mhig [mailto:notifications@github.com]
_Sent:_ vrijdag 13 juni 2014 10:08
_To:_ ircwash/WASHCost-tool
_Cc:_ Nicolas Dickinson
_Subject:_ Re: [WASHCost-tool] OAuth: Cannot use default authorization_code
grant method // please check (#16)

Doorkeeper docs should not be used for this - that is the underlying
library and it has different settings and options depending on what you are
trying to achieve.

This is a standard OAuth2 setup.
1. An application is setup on the WASHcost system with a callback url
   (callback url is an endpoint on the request server)
2. Keys are generated for this application
3. The Application makes a request with these keys and it’s callback url
4. WASHCcost system authorises and posts back to the supplied callback
   url the necessary access token
5. The Application then has this token which was consumed by it’s URL
6. Using this token and passing it with each request it can then access
   the various API endpoints

Users requiring access to the API should write standard OAuth2 logic to
interface with it.

—
Reply to this email directly or view it on GitHub
https://github.com/ircwash/WASHCost-tool/issues/16#issuecomment-45985867.

## 

http://www.irc.nl/page/73684

**Comment by nickdickinson** [comment]
I'm reopening based on my previous comment, the faulty URL

**Comment by nickdickinson** [comment]
Ok, So I retested and suspected the way I was posting the variables. I am now able to retrieve a token with an authorisation code. It would still be useful to add to the documentation
