### ISSUE TITLE
REPORT PAGE GRAPH: Overlap of currency values with Y-axis label

### ISSUE THREAD

**Issue by peterburr** [ircwash/WASHCost-tool#19]
WHEN the y-axis values are large (6+ digits) they overlap with the y-axis label recurrent costs.

**Comment by mhig** [comment]
Can you please send a picture of this issue? I haven't been able to replicate.

**Comment by peterburr** [comment]
Hi Matthew,

Please see screen grab below:

![image](https://cloud.githubusercontent.com/assets/7868305/3298110/592246f6-f5fd-11e3-911e-f10c4cda7c78.png)

If that doesn't work then you may be able to view the problem here:

http://washcost.herokuapp.com/en/report/53a0030b6d606ff3f300000a

**Comment by mhig** [comment]
Resolved.
