### ISSUE TITLE
ADVANCED: Water & San Inputs COPY CHANGE: Recurrent Expenditure

### ISSUE THREAD

**Issue by peterburr** [ircwash/WASHCost-tool#2]
Copy Change:
FROM: What has been/will be the minor operation expenditure? 
TO: What has been/will be the minor operation expenditure (per year)? 

FROM: What has been/will be spent on capital maintenance expenditure?
TO: What has been/will be spent on capital maintenance expenditure (per year)?

FROM: What is the cost servicing any loans taken to fund the service?
TO: What is the cost servicing any loans taken to fund the service (per year)?

**Comment by mhig** [comment]
These have been updated, as per the ticketed request.
