### ISSUE TITLE
REPORT PAGE GRAPH: Missing explanatory text below the graph

### ISSUE THREAD

**Issue by peterburr** [ircwash/WASHCost-tool#20]
Part of the graphical output should be a text report directly below the graph based on inputted values. This is in the final worked up copy + wireframes and is aslong the lines of: "the recurrent cost of running the system over a 30 year period are X per person at current prices - or Y per person per year......."

**Comment by mhig** [comment]
This would be displayed in entered prices (currency and year of expenditure).

Nick: Can you confirm that this feature is required?

**Comment by nickdickinson** [comment]
Ok, regarding reporting it in the same currency and year.

_From:_ mhig [mailto:notifications@github.com]
_Sent:_ 17 June 2014 06:44
_To:_ ircwash/WASHCost-tool
_Subject:_ Re: [WASHCost-tool] REPORT PAGE GRAPH: Missing explanatory text
below the graph (#20)

This would be displayed in entered prices (currency and year of expenditure)

—
Reply to this email directly or view it on GitHub
https://github.com/ircwash/WASHCost-tool/issues/20#issuecomment-46266725.[image:
Image removed by sender.]

## 

http://www.irc.nl/page/73684

**Comment by mhig** [comment]
It was agreed with Nick that it was not a must feature.

**Comment by nickdickinson** [comment]
Ok, it is not a must feature as long as we have those different figures
available on the report page header and in the expenditure data.

_From:_ mhig [mailto:notifications@github.com]
_Sent:_ 20 June 2014 09:41
_To:_ ircwash/WASHCost-tool
_Cc:_ Nicolas Dickinson
_Subject:_ Re: [WASHCost-tool] REPORT PAGE GRAPH: Missing explanatory text
below the graph (#20)

It was agreed with Nick that it was not a must feature.

—
Reply to this email directly or view it on GitHub
https://github.com/ircwash/WASHCost-tool/issues/20#issuecomment-46652595.[image:
Image removed by sender.]

## 

http://www.irc.nl/page/73684
