### ISSUE TITLE
Basic Reports - Comparison in the dashboard is reported as 0 USD 

### ISSUE THREAD

**Issue by nickdickinson** [ircwash/WASHCost-tool#21]
Saving this report results in 0 USD being reported in the dashboard even though all the cost values are there.
http://washcost.herokuapp.com/en/report/539ec86227795ac327000022

![image](https://cloud.githubusercontent.com/assets/1900032/3285997/05c6de74-f542-11e3-8cc4-acb1092fa28f.png)

**Comment by mhig** [comment]
For basic reports, this figure should be "-" as the basic tool comparisons are not provided. This will be adjusted.
