### ISSUE TITLE
Advanced tool - comparison value in dashboard is unclear

### ISSUE THREAD

**Issue by nickdickinson** [ircwash/WASHCost-tool#22]
It is not clear what comparison is shown in the dashboard currently.
Please change this value to the TOTAL 30 YEAR EXPENDITURE / ACTUAL POPULATION

**Comment by mhig** [comment]
Should the title reflect this as well?

**Comment by nickdickinson** [comment]
The title can be "Expenditure per person (30 years)"

**Comment by mhig** [comment]
This will now be updated to show the following on the dashboard as per email from Nick:

> Capital expenditure per person (USD 2011)
> Recurrent expenditure per person per year (USD 2011)
> Population meeting all national service norms 

NOT "Expenditure per person (30 years)"
