### ISSUE TITLE
Basic report - read full review is showing

### ISSUE THREAD

**Issue by nickdickinson** [ircwash/WASHCost-tool#24]
Please hide the "read full review" link and text. At the moment, this text adds a big overhead to translation and copy and it is not always appropriate depending how the report is used.

**Comment by mhig** [comment]
Please clarify that this text should be removed entirely from the tool. 

This was a large part of the design, feedback and implementation. It currently does hide and reveal based on the user selection.

**Comment by nickdickinson** [comment]
Hi Matthew,

That is correct. However, unfortunately we realised in the last round of
testing that it wasn't adding a lot to the visual reporting and required a
lot of editing and translation to add languages or to deal with content
issues.

Confirmed.
On 17 Jun 2014 05:13, "mhig" notifications@github.com wrote:

> Please clarify that this text should be removed entirely from the tool.
> 
> This was a large part of the design, feedback and implementation. It
> currently does hide and reveal based on the user selection.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ircwash/WASHCost-tool/issues/24#issuecomment-46263123
> .

## 

http://www.irc.nl/page/73684

**Comment by mhig** [comment]
We will look at commenting this feature out.

Thanks,
Matthew.

**Comment by nickdickinson** [comment]
THanks

_From:_ mhig [mailto:notifications@github.com]
_Sent:_ 17 June 2014 08:12
_To:_ ircwash/WASHCost-tool
_Cc:_ Nicolas Dickinson
_Subject:_ Re: [WASHCost-tool] Basic report - read full review is showing
(#24)

We will look at commenting this feature out.

Thanks,
Matthew.

From: Nicolas Dickinson notifications@github.com<mailto:
notifications@github.com>>
Reply-To: ircwash/WASHCost-tool reply@reply.github.com<mailto:
reply@reply.github.com>>
Date: Monday, 16 June 2014 23:08
To: ircwash/WASHCost-tool WASHCost-tool@noreply.github.com<mailto:
WASHCost-tool@noreply.github.com>>
Cc: Matthew Higham matthew@native.commailto:matthew@native.com>
Subject: Re: [WASHCost-tool] Basic report - read full review is showing
(#24)

Hi Matthew,

That is correct. However, unfortunately we realised in the last round of
testing that it wasn't adding a lot to the visual reporting and required a
lot of editing and translation to add languages or to deal with content
issues.

Confirmed.
On 17 Jun 2014 05:13, "mhig" notifications@github.com<mailto:
notifications@github.com>> wrote:

> Please clarify that this text should be removed entirely from the tool.
> 
> This was a large part of the design, feedback and implementation. It
> currently does hide and reveal based on the user selection.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ircwash/WASHCost-tool/issues/24#issuecomment-46263123
> 
> .

## 

http://www.irc.nl/page/73684

—
Reply to this email directly or view it on GitHub<
https://github.com/ircwash/WASHCost-tool/issues/24#issuecomment-46270623>.

This email and any attachments to it may be confidential and are intended
solely for the use of the individual to whom it is addressed. Any views or
opinions expressed are solely those of the author and do not necessarily
represent those of Native. If you are not the intended recipient of this
email, you must neither take any action based upon its contents, nor copy
or show it to anyone.
Please contact the sender if you believe you have received this email in
error.
Native Design Ltd.
Company Registration Number: 3703075.
Place of Registration: England.
Registered Office Address: 5 Garden Walk, London EC2A 3EQ, England.

—
Reply to this email directly or view it on GitHub
https://github.com/ircwash/WASHCost-tool/issues/24#issuecomment-46270827.[image:
Image removed by sender.]

## 

http://www.irc.nl/page/73684

**Comment by nickdickinson** [comment]
I see it has been removed from water. The sanitation tool is still showing this feature. Can it be removed?

![image](https://cloud.githubusercontent.com/assets/1900032/3324389/39bb80f8-f77d-11e3-88d3-ddf48165e108.png)
