### ISSUE TITLE
Advanced tool report: status variable not linked to questionnaire status variable

### ISSUE THREAD

**Issue by nickdickinson** [ircwash/WASHCost-tool#25]
The status variable of a report does not show up correctly in the dashboard when assigned to the report.

To reproduce, go to this shared report (all empty except the status), save it, and check the dashboard:
http://washcost.herokuapp.com/en/report/539ee3dd27795ac327000026

![image](https://cloud.githubusercontent.com/assets/1900032/3287058/6b011678-f552-11e3-90f6-af9a8d847758.png)

In the dashboard it is not reported as existing:

![image](https://cloud.githubusercontent.com/assets/1900032/3287065/900a8166-f552-11e3-89be-da25db8a0a09.png)

I would suggest to use a single variable instead of having two separate ones.

**Comment by mhig** [comment]
Merge with #25
