### ISSUE TITLE
ADVANCED: Water & San Inputs: (i) tabs not working

### ISSUE THREAD

**Issue by peterburr** [ircwash/WASHCost-tool#3]
Information (i) tabs are not working

**Comment by mhig** [comment]
On which page is this happening?

**Comment by peterburr** [comment]
All pages

**Comment by mhig** [comment]
OK - can you add more information?

Does the i not appear, or is it simply that there is no copy on it? Does the i roll out?

Please also tell us which browser you are using and platform.

**Comment by peterburr** [comment]
Using Google Chrome. The (i) symbols appear and you can select them. Problem is the pop out says "tip here" but no content is provided.

**Comment by mhig** [comment]
Hi Peter, Thanks for the additional information. THis is a YAML issue and will be resolved in short order. Thanks, M

**Comment by peterburr** [comment]
Thanks.

**Comment by mhig** [comment]
This issue has been resolved with the latest YAML integration
