### ISSUE TITLE
Advanced tool report BOTH: Percentile graph comparisons are missing

### ISSUE THREAD

**Issue by nickdickinson** [ircwash/WASHCost-tool#33]
None of the reports generate the percentile comparisons at the moment. 

While the currency conversion is on the dashboard, this is not a comparison between reports based on technology, recurrent cost and capital costs as in the wire frames.

One would have to save a shared report before making any manual comparison. At minimum, I would expect the percentile comparison with the user's own reports.

**Comment by mhig** [comment]
As discussed, this will now be resolved in #22
