### ISSUE TITLE
API: Cannot delete a report

### ISSUE THREAD

**Issue by nickdickinson** [ircwash/WASHCost-tool#34]
This functionality would mean adding one endpoint:
/api/delete/:id

This would be extremely helpful if very easy. It would also allow an administrator with access to an app to delete reports with problems.

We can nearly do CRUD (create, read, update, delete) and without the delete, we won't be able to manage the created reports as effectively.

**Comment by mhig** [comment]
As agreed, this will be done via the main application UI

**Comment by nickdickinson** [comment]
Yes, with the only caveat that at minimum we should be able to fix broken
reports with the UPDATE statement in the API and the right formatting. The
main problem is when a dashboard breaks because of a report and then we
cannot fix it.

On 19 June 2014 08:49, mhig notifications@github.com wrote:

> As agreed, this will be done via the main application UI
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ircwash/WASHCost-tool/issues/34#issuecomment-46528764
> .

## 

Nicolas Dickinson
Senior Programme Officer
Monitoring and IT Expert

Postal address:
P.O. Box 82327
2508 EH The Hague
The Netherlands

http://www.ircwash.org

T: +31 70 304 4038
M: +31 649875488
Twitter: @waternote

http://www.twitter.com/waternote

## 

http://www.irc.nl/page/73684
