### ISSUE TITLE
SHARE link provided to user with mask to www.ircwash.org/washcost?url=

### ISSUE THREAD

**Issue by nickdickinson** [ircwash/WASHCost-tool#36]
The report link is provided to the user from this HAML template (if I am correct). 

https://github.com/ircwash/WASHCost-tool/blob/ca1d1d3797bf042bbba79531a1de9f2f768b1237/app/views/shared/share_report.html.haml

QUESTION: can we make it is that the code will instead provide a link in the following format:
http://www.ircwash.org/washcost?url=http%3A%2F%2Fwashcost.herokuapp.com%2Fen%2Freport%2F53a182208f2f456477000001

I'm not Ruby developer but perhaps something like changing line 7 to:

= link_to "http://www.ircwash.org/washcost?url=" + CGI.escape( "#{request.protocol}#{request.host_with_port}" + reports_load_path( I18n.locale, @report.id ) ), "http://www.ircwash.org/washcost?url=" + CGI.escape( "#{request.protocol}#{request.host_with_port}" + reports_load_path( I18n.locale, @report.id ) ), { :class => 'share_report--link' }

**Comment by mhig** [comment]
Hi Sheila,

I have run this past the developers, and their response was positive. I
have copied it below:

Yes you can do what they want, you just need to update the link that is
output for the shared report in the code and you will need to make sure
the site with the iframe can do the necessary functions to pass this query
string through to the iframe as the URL.

Hope that helps.

Thanks,
Matthew.

**Comment by mhig** [comment]
Native is waiting on confirmation of the URL.

**Comment by mhig** [comment]
This is completed, and includes language specifier.
