### ISSUE TITLE
BASIC TOOL WATER: technology information box

### ISSUE THREAD

**Issue by nickdickinson** [ircwash/WASHCost-tool#38]
The French and English information boxes on the basic tool technology page are missing. The copy is there but I think there is a syntax error in the YAML. It works in the sanitation basic tool for example.

![image](https://cloud.githubusercontent.com/assets/1900032/3324282/a0aa68d6-f77a-11e3-8eca-f9e6a6ff77dd.png)

**Comment by mhig** [comment]
Hi Nick, It looks like the YAML have been updated. I note the comment in the YAML:

```
      #added info: assuming the same syntax as for water. 
```

YAML's need to be parsed into the system where they have been restructured. Did you make any changes to these files?

**Comment by nickdickinson** [comment]
Hi Matthew,

Thanks. I sent an email yesterday with the only changes I have made.

Does this mean the technology text should be visible now in the water tool?
The information box is still blank. Not sure about the comment as
sanitation is working fine but it’s actually the water tool that has the
missing information.

Please let me know when it is safe to continue with copy? I’m aiming for
Sunday evening. Thanks!

Best,

Nick

_From:_ mhig [mailto:notifications@github.com]
_Sent:_ 20 June 2014 07:50
_To:_ ircwash/WASHCost-tool
_Cc:_ Nicolas Dickinson
_Subject:_ Re: [WASHCost-tool] BASIC TOOL WATER: technology information box
(#38)

Hi Nick, It looks like the YAML have been updated. I note the comment in
the YAML:

```
  #added info: assuming the same syntax as for water.
```

YAML's need to be parsed into the system where they have been restructured.
Did you make any changes to these files?

—
Reply to this email directly or view it on GitHub
https://github.com/ircwash/WASHCost-tool/issues/38#issuecomment-46646798.[image:
Image removed by sender.]

## 

http://www.irc.nl/page/73684
