### ISSUE TITLE
BASIC TOOL FRENCH REPORT : no answer provided

### ISSUE THREAD

**Issue by nickdickinson** [ircwash/WASHCost-tool#40]
The French report in the basic tool does not seem to be picking up the  no_answer_provided translation. It is showing the English and not the French YAML for that .
http://washcost.herokuapp.com/fr/report/53a2861950ec8ace8a000002

![image](https://cloud.githubusercontent.com/assets/1900032/3324375/b65d0c90-f77c-11e3-980a-104ff5671a03.png)

**Comment by mhig** [comment]
Resolved with latest release.
