### ISSUE TITLE
Advanced: Currency Conversion - Euro + Australian Dollar - maybe more

### ISSUE THREAD

**Issue by peterburr** [ircwash/WASHCost-tool#41]
I have done a sample test of of different currencies and whether the conversion to the US$ are shown on the Dashboard. I tested the following currencies in 2011 - all of these have reported values in look up table so should work:
GBP - OK
Yen - OK
Diram - OK
Lek - OK
Canadian Dollar - OK
Australian Dollar - Gives N/A on dashboard
Euro - Gives N/A on dashboard

This was only a sample of countries and years so other issues are likely to exist

**Comment by nickdickinson** [comment]
This may be related to the country selected if it required converting back
to the local currency first according to the current equations, which will
also require a value. Would be best to stick to one country that surely has
the GDP deflator for now.

In other words, the app should be smart enough not to convert to the
country currency and apply the GDP deflator multiplier of 1 (which may be
missing data), when the year is 2011.

Nick

On 24 June 2014 11:04, peterburr notifications@github.com wrote:

> I have done a sample test of of different currencies and whether the
> conversion to the US$ are shown on the Dashboard. I tested the following
> currencies in 2011 - all of these have reported values in look up table so
> should work:
> GBP - OK
> Yen - OK
> Diram - OK
> Lek - OK
> Canadian Dollar - OK
> Australian Dollar - Gives N/A on dashboard
> Euro - Gives N/A on dashboard
> 
> This was only a sample of countries and years so other issues are likely
> to exist
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ircwash/WASHCost-tool/issues/41.

## 

Nicolas Dickinson
Senior Programme Officer
Monitoring and IT Expert

Postal address:
P.O. Box 82327
2508 EH The Hague
The Netherlands

http://www.ircwash.org

T: +31 70 304 4038
M: +31 649875488
Twitter: @waternote

http://www.twitter.com/waternote

## 

http://www.irc.nl/page/73684

**Comment by peterburr** [comment]
In these cases the data was reported in it's own country. ie. the report was for a system in Australia with the Aus dollar, the euro was for a system in spain

**Comment by nickdickinson** [comment]
The Exchange rate to a local currency for countries in the Euro zone will
not work as currently coded, as we do not have exchange rates for those
countries.

Perhaps the easy solution would be to copy all the exchange rates from
Europe to those countries to fill in the table when looking up FX by
country. I'm not sure why AUS is not working. Matthew will need to comment
on whether we can add values to the FX look up table.

On 24 June 2014 11:21, peterburr notifications@github.com wrote:

> I In these cases the data was reported in it's own country. ie. the report
> was for a system in Australia with the Aus dollar, the euro was for a
> system in spain
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ircwash/WASHCost-tool/issues/41#issuecomment-46949523
> .

## 

Nicolas Dickinson
Senior Programme Officer
Monitoring and IT Expert

Postal address:
P.O. Box 82327
2508 EH The Hague
The Netherlands

http://www.ircwash.org

T: +31 70 304 4038
M: +31 649875488
Twitter: @waternote

http://www.twitter.com/waternote

## 

http://www.irc.nl/page/73684

**Comment by peterburr** [comment]
RE: Euro values - yes that would work

**Comment by mhig** [comment]
This has been updated to include EUU from the UN (Nick provided a manual modification to the CSV) and corrected the country/currency look up
