### ISSUE TITLE
Advanced: Deflator values - US$ values deflator error

### ISSUE THREAD

**Issue by peterburr** [ircwash/WASHCost-tool#43]
I have been testing the deflator conversions from historic values to 2011 on the dashboard. I have run 10 scenarios varying currencies and years. All of these have worked as expected except for values where the original currency is given as the US$.

I have run three different cases with US$ varying the year each time - but leaving all input cost values the same. The results given on the dashboard (for CapEx per person) are:

2001 = US$ 3.39 
2005 = US$ 4.00
2011 = US$ 4.10

This is incorrect - due to inflation the historical expenditure values should equate to a greater current cost in today's terms. 

Referring to the deflator factor sheet:

If US$4.10 had been spent in 2001 - this would equal US$ 5.08 (deflator factor 1.24) in 2011

If  US$4.10 had been spent in 2005 - this would equal US$ 4.67 (deflator factor 1.14) in 2011

This has only been observed in relation to US$ (the values for GBP and Yen behaved as expected). However similar issues may exist for other currencies.

**Comment by mhig** [comment]
This issue has been resolved
