### ISSUE TITLE
API: Updating status in questionnaire does not update dashboard

### ISSUE THREAD

**Issue by nickdickinson** [ircwash/WASHCost-tool#44]
Using the API, I'm able to update existing reports by change the title and by changing some values in the questionnaire. However, when I update the report status in the question to 3 "Historical expenditure", it does not reflect this update in the dashboard (they seem to be unlinked). I can get both status variables with the different values (0 and 3) but I can't seem to update the status variable which appears on the dashboard. If I could update both then I could ensure they stay the same.

**Comment by mhig** [comment]
Will look into this now.

Thanks,
Matthew.

**Comment by mhig** [comment]
A fix has been pushed for this.
