### ISSUE TITLE
Currency units changing on report page

### ISSUE THREAD

**Issue by nickdickinson** [ircwash/WASHCost-tool#46]
http://washcost.herokuapp.com/en/report/53a9cb55676012012d00000a
http://washcost.herokuapp.com/en/report/53a9c463676012012d000003

MZN in this example become MTn

Also, changing the currency to others creates equally strange conversions of the letters.

MWK becomes MK

USD becomes $ (not a problem but also not required)

Is this on purpose? What standard is this?

For consistency, please use the same letters as the input and put a space between the letters and the number.

**Comment by nickdickinson** [comment]
Not a bug. these are standards

**Comment by mhig** [comment]
This is displaying standard currency symbols
