### ISSUE TITLE
ADVANCED BOTH: benchmarks not converted to local currency

### ISSUE THREAD

**Issue by nickdickinson** [ircwash/WASHCost-tool#47]
I found a pretty major issue in the calculations. See:
http://washcost.herokuapp.com/en/report/53ac053e9a55a60477000001

In this example, the benchmarks are being applied without conversion to the local currency and year (opposite of the current equation)...

You would have to convert a value of 1 (in local currency and year) to USD 2011 to get a factor. The correct benchmarks are

direct_support_benchmark_local = direct_support_benchmark_USD_2011 / final_usd_2011(questionnaire, 1)

OpEx_benchmark_local = OpEx_benchmark_USD_2011 / final_usd_2011(questionnaire, 1)

**Comment by mhig** [comment]
Resolved.
