### ISSUE TITLE
ADVANCED BOTH: Don't know check box can be selected and the text input still works (MINOR)

### ISSUE THREAD

**Issue by nickdickinson** [ircwash/WASHCost-tool#49]
The "Don't know" check box should disactivate input in the text box to work correctly.

When ticking the check box, the text box is deleted correctly, but it is still possible to fill in a value and it becomes ambiguous as to whether the answer is don't know or if it is the value written in afterwards. if one tries to make it clear by unchecking the box, then the text field is deleted which is inconvenient.

**Comment by mhig** [comment]
"NICE TO HAVE"

**Comment by mhig** [comment]
Resolved in latest release
