### ISSUE TITLE
ADVANCED: Water & San "Summary" Report: Use of Comma separator for large numbers 

### ISSUE THREAD

**Issue by peterburr** [ircwash/WASHCost-tool#5]
Large numbers (four digits or more) should use common separators.

Relevant to: 
TOTAL EXPENDITURE FOR 30 YEARS  
and directly below this "XXXX people" served

**Comment by nickdickinson** [comment]
Yes, this is part of the application of the user's locale. Matthew, can you please show values in the user locale with commas for example? so instead of 10000, you would show 10,000 to the EN-GB locale or 10.000 if in a DE-de or for FR it would be 10 000

**Comment by mhig** [comment]
We will look to enable this for EN and FR, which are both in scope.

**Comment by nickdickinson** [comment]
Thanks. Please do this in a way that we can extend it when new languages
are added.

_From:_ mhig [mailto:notifications@github.com]
_Sent:_ 17 June 2014 07:03
_To:_ ircwash/WASHCost-tool
_Cc:_ Nicolas Dickinson
_Subject:_ Re: [WASHCost-tool] ADVANCED: Water & San "Summary" Report: Use
of Comma separator for large numbers (#5)

We will look to enable this for EN and FR, which are both in scope.

—
Reply to this email directly or view it on GitHub
https://github.com/ircwash/WASHCost-tool/issues/5#issuecomment-46267526.[image:
Image removed by sender.]

## 

http://www.irc.nl/page/73684
