### ISSUE TITLE
ADVANCED TOOL: Service level calculations not working correctly

### ISSUE THREAD

**Issue by nickdickinson** [ircwash/WASHCost-tool#50]
The following report shows that the service level calculations are not working as in the test cases and the provided excel sheet:

http://washcost.herokuapp.com/en/report/53ac829ab0a36d4fa0000002

In this case only one of the service shares achieved the national norm on all indicators and this was 27% yet the report shows 37%.

**Comment by nickdickinson** [comment]
I can replicate in sanitation:
http://washcost.herokuapp.com/en/report/53ac85a0b0a36d4fa0000004

**Comment by mhig** [comment]
This has been resolved and committed to the master branch.
