### ISSUE TITLE
BASIC SANITATION: Cannot save a basic sanitation report

### ISSUE THREAD

**Issue by nickdickinson** [ircwash/WASHCost-tool#64]
While trying to save a basic sanitation report, after filling in the name and clicking save, an error screen appears. It is hard to trace when this started but I can confirm it is probably after the last release by Native and deployment as it does not work on the IRC website nor the Native test server:
![image](https://cloud.githubusercontent.com/assets/1900032/3932822/4b20e0d2-2472-11e4-97ea-9086e892900d.png)

I have an account with a basic sanitation report saved that was created recently. Probably it was created on the 2.0 release (25 June) or 2.1 (27 June) release and then the error was introduced in 2.1 or 2.2 (29 June) and not caught in the follow testing of the minor changes.

**Comment by nickdickinson** [comment]
I cannot consistently reproduce this error. Suddenly I was able to save reports and then it stopped again. 

I have not found the exact conditions that cause this but once the error starts, it affects all basic sanitation reports I try to save. Clearing cookies and re logging in does not seem to work to stop the errors.

**Comment by mhig** [comment]
Issues resolved
