### ISSUE TITLE
ADVANCED: Affordability Traffic Lights - Incorrect reporting

### ISSUE THREAD

**Issue by peterburr** [ircwash/WASHCost-tool#7]
Traffic lights report "affordable" when % values are well above guidelines. I have stress tested this and it seems % thresholds are a order of magnitude out.

**Comment by mhig** [comment]
Hi Peter - can you confirm that the numbers are correct within the calculation?

**Comment by peterburr** [comment]
Percentages and cost values are correct. The traffic light graphic is incorrect

**Comment by mhig** [comment]
Thank you. And the affordability copy is correct as well?

**Comment by peterburr** [comment]
Nick and talked about changing copy - I think he will be providing the final input on that

**Comment by mhig** [comment]
Bug resolved and verified.
