### ISSUE TITLE
ADVANCED: Sanitation "service area" inputs - COPY CHANGE

### ISSUE THREAD

**Issue by peterburr** [ircwash/WASHCost-tool#8]
Question title missing. Change:

FROM: Label
TO: Who safeguards the operation and maintenance of the infrastructure?

**Comment by mhig** [comment]
This has been updated, as per the ticketed request.

**Comment by peterburr** [comment]
In the sanitation input it still report "label" and not "Who safeguards the operation and maintenance of the infrastructure?"

**Comment by mhig** [comment]
Resolved.
