### ISSUE TITLE
ADVANCED: Water & San - BUG on report page -  affordability inputted expenditure design user - Cost of Capital 

### ISSUE THREAD

**Issue by peterburr** [ircwash/WASHCost-tool#9]
IF input question: What is the average annual household income in the service area? is left blank

THEN on report page, under affordability inputted expenditure design users set of outputs, the Cost of Capital value is given as 666%. 

This is incorrect and should report "There's no data for this"

**Comment by mhig** [comment]
Resolved in latest release

**Comment by peterburr** [comment]
This still reports 666% for design number of users when the household income value is missing

**Comment by mhig** [comment]
Resolved.
